mod keyword;

pub use keyword::{
    search_keyword, SearchEmbeddingConfig, ProjectSearchResponse, ProjectSearchResult,
    SearchImageRef,
};

use std::collections::HashMap;
use std::fs;
use std::path::Path;

use walkdir::WalkDir;

use crate::hybrid::{merge_rrf, RankedItem};
use crate::vector::{search_vector, VectorHit};

/// Hybrid search: keyword (always) + vector (when an embedding is supplied).
///
/// `query_embedding` is generated by the HTTP layer (reqwest) and passed in;
/// common does no HTTP. When `query_embedding` is `None` — or vector search
/// fails for any reason (no table, dim mismatch, IO error) — the function
/// **degrades to keyword-only and never returns an error on the vector side**.
/// Only keyword-side failures (bad project path) propagate as `Err`.
///
/// `mode` in the response is `"hybrid"` when vectors contributed, else
/// `"keyword"`. `vector_hits` counts vector results that survived fusion.
pub async fn hybrid_search(
    project_path: String,
    query: String,
    top_k: usize,
    include_content: bool,
    query_embedding: Option<Vec<f32>>,
) -> Result<ProjectSearchResponse, String> {
    // Fetch a wider candidate pool from each channel so fusion has room to
    // reorder; truncate to top_k at the end.
    let pool = (top_k * 2).max(top_k + 5);

    let keyword_response = search_keyword(
        project_path.clone(),
        query.clone(),
        pool,
        include_content,
    )?;

    // Attempt vector search; any failure degrades to keyword-only.
    let vector_hits: Vec<VectorHit> = match query_embedding.as_deref() {
        Some(emb) if !emb.is_empty() => match search_vector(&project_path, emb, pool).await {
            Ok(hits) => hits,
            Err(e) => {
                eprintln!("[search] vector search unavailable, degrading to keyword: {e}");
                Vec::new()
            }
        },
        _ => Vec::new(),
    };

    if vector_hits.is_empty() {
        // Pure keyword. Truncate to top_k (search_keyword already clamps, but
        // be explicit in case pool > top_k).
        let mut results = keyword_response.results;
        results.truncate(top_k);
        return Ok(ProjectSearchResponse {
            mode: "keyword".to_string(),
            token_hits: keyword_response.token_hits,
            vector_hits: 0,
            results,
        });
    }

    // Build page_id -> wiki relpath map so vector hits can be fused against
    // keyword results (which key on relpath) and enriched.
    let page_map = build_page_id_map(&project_path);

    let keyword_keys: Vec<String> = keyword_response
        .results
        .iter()
        .map(|r| r.path.clone())
        .collect();
    let keyword_by_path: HashMap<String, ProjectSearchResult> = keyword_response
        .results
        .into_iter()
        .map(|r| (r.path.clone(), r))
        .collect();

    // Vector hits → (relpath, distance). Skip hits whose page_id has no file
    // (e.g. wiki page deleted after indexing).
    let vector_keys: Vec<(String, f32)> = vector_hits
        .iter()
        .filter_map(|h| page_map.get(&h.page_id).map(|p| (p.clone(), h.distance)))
        .collect();

    // Also index vector hits by relpath for enrichment of vector-only items.
    let vector_by_path: HashMap<String, &VectorHit> = vector_hits
        .iter()
        .filter_map(|h| page_map.get(&h.page_id).map(|p| (p.clone(), h)))
        .collect();

    let fused: Vec<RankedItem> = merge_rrf(keyword_keys, vector_keys, top_k);

    let mut results: Vec<ProjectSearchResult> = Vec::with_capacity(fused.len());
    let mut vector_hits_used = 0usize;
    for item in &fused {
        let has_vector = item.vector_rank.is_some();
        if has_vector {
            vector_hits_used += 1;
        }
        let result = build_result(
            item,
            &keyword_by_path,
            &vector_by_path,
            &project_path,
            include_content,
        );
        results.push(result);
    }

    Ok(ProjectSearchResponse {
        mode: "hybrid".to_string(),
        token_hits: keyword_response.token_hits,
        vector_hits: vector_hits_used,
        results,
    })
}

/// Map a wiki page stem (page_id, = filename without `.md`) to its relpath
/// under `<project>/wiki/`. Walks the tree once. First match wins on stem
/// collision (rare; ingest keys chunks on stem so duplicates are already
/// ambiguous upstream).
fn build_page_id_map(project_path: &str) -> HashMap<String, String> {
    let mut map = HashMap::new();
    let wiki_root = Path::new(project_path).join("wiki");
    if !wiki_root.exists() {
        return map;
    }
    for entry in WalkDir::new(&wiki_root).into_iter().filter_map(Result::ok) {
        if !entry.file_type().is_file() {
            continue;
        }
        if entry.path().extension().and_then(|s| s.to_str()) != Some("md") {
            continue;
        }
        let Some(stem) = entry.path().file_stem().and_then(|s| s.to_str()) else {
            continue;
        };
        let rel = keyword::relative_to_project(project_path, entry.path());
        map.entry(stem.to_string()).or_insert(rel);
    }
    map
}

/// Build a `ProjectSearchResult` from a fused `RankedItem`.
///
/// - If the item has a keyword hit, reuse its enriched title/snippet/images
///   (and content if requested), and attach `vector_score` when it also
///   matched in the vector index.
/// - If the item is vector-only, enrich from the wiki file on disk: title and
///   images from the file, snippet from the matched `chunk_text`.
fn build_result(
    item: &RankedItem,
    keyword_by_path: &HashMap<String, ProjectSearchResult>,
    vector_by_path: &HashMap<String, &VectorHit>,
    project_path: &str,
    include_content: bool,
) -> ProjectSearchResult {
    let vhit = item.vector_rank.and_then(|_| vector_by_path.get(&item.key));

    if let Some(kw) = keyword_by_path.get(&item.key) {
        // Keyword hit (possibly also vector). Reuse enrichment, attach score.
        let mut result = kw.clone();
        if let Some(v) = vhit {
            result.vector_score = Some(v.distance);
        }
        // Keyword score stays as the BM25-ish score; RRF ordering already
        // happened. Preserve score for display ranking.
        return result;
    } else if let Some(v) = vhit {
        // Vector-only: enrich from file.
        let abs = Path::new(project_path).join(&item.key);
        let content = fs::read_to_string(&abs).unwrap_or_default();
        let file_name = abs
            .file_name()
            .and_then(|s| s.to_str())
            .unwrap_or("");
        let title = keyword::extract_title(&content, file_name);
        let images = keyword::extract_image_refs(&content);
        ProjectSearchResult {
            path: item.key.clone(),
            title,
            snippet: keyword::build_snippet(&v.chunk_text, &v.chunk_text),
            title_match: false,
            score: 0.0,
            vector_score: Some(v.distance),
            images,
            content: include_content.then_some(content),
        }
    } else {
        // Fallback (shouldn't happen — fused items come from one of the two
        // lists): emit a minimal placeholder so we never panic.
        ProjectSearchResult {
            path: item.key.clone(),
            title: item.key.clone(),
            snippet: String::new(),
            title_match: false,
            score: 0.0,
            vector_score: None,
            images: Vec::new(),
            content: None,
        }
    }
}
